name: build-c001apk-Android-txz

on:
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
      - name: Install dependencies
        run: flutter pub get
      - name: Build c001apk APK
        run: flutter build apk --release --split-per-abi --obfuscate --split-debug-info=build/debug_info --tree-shake-icons
      - name: Pack APKs with tar.xz
        run: |
          export XZ_OPT="-9 -T8"
          tar -cJf build-c001apk-Android.tar.xz -C build/app/outputs/flutter-apk/ .
      - name: Pack debug symbols with tar.xz
        run: |
          export XZ_OPT="-9 -T8"
          tar -cJf debug_info.tar.xz -C build/debug_info .
      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: c001apk-Android.txz
          path: build-c001apk-Android.tar.xz
      - name: Upload debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: build-c001apk-Android-debug_info.txz
          path: debug_info.tar.xz