name: c001apk-Kotlin-Java-安卓构建

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/**'

jobs:
  构建:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 解压 c001apk-Kotlin-Java.tar.xz
        run: tar -xvf c001apk-Kotlin-Java.tar.xz

      - name: 设置工作目录
        run: echo "项目目录=c001apk-Kotlin-Java" >> $GITHUB_ENV

      - name: Gradle包装器验证
        uses: gradle/actions/wrapper-validation@v3
        with:
          working-directory: ${{ env.项目目录 }}

      - name: 安装 JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: 缓存 Gradle 依赖
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-core-${{ hashFiles('**/build.gradle.kts', '**/build.gradle', '**/libs.versions.toml') }}
          restore-keys: |
            gradle-deps

      - name: 授予 gradlew 执行权限
        working-directory: ${{ env.项目目录 }}
        run: chmod +x gradlew

      - name: 构建发布版 APK
        id: 构建发布版
        working-directory: ${{ env.项目目录 }}
        run: |
          ./gradlew :app:assembleRelease
          echo "发布版名称=$(ls app/build/outputs/apk/release/*.apk | awk -F '(/|\\.apk)' '{print $6}')" >> $GITHUB_OUTPUT

      - name: 用 xz 打包发布版 APK
        working-directory: ${{ env.项目目录 }}
        run: |
          cd app/build/outputs/apk/release
          tar -cvf - *.apk | xz -9 -T8 > 发布版_apk.tar.xz

      - name: 上传发布版 APK 压缩包 (tar.xz)
        uses: actions/upload-artifact@v4
        with:
          name: 发布版_apk_xz
          path: "${{ env.项目目录 }}/app/build/outputs/apk/release/发布版_apk.tar.xz"

      - name: 上传原始发布版 APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.构建发布版.outputs.发布版名称 }}
          path: "${{ env.项目目录 }}/app/build/outputs/apk/release/*.apk"

      - name: 上传混淆映射文件
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: 混淆映射
          path: "${{ env.项目目录 }}/app/build/outputs/mapping/release"

      - name: 构建调试版 APK
        id: 构建调试版
        working-directory: ${{ env.项目目录 }}
        run: |
          ./gradlew :app:assembleDebug
          echo "调试版名称=$(ls app/build/outputs/apk/debug/*.apk | awk -F '(/|\\.apk)' '{print $6}')" >> $GITHUB_OUTPUT

      - name: 用 xz 打包调试版 APK
        working-directory: ${{ env.项目目录 }}
        run: |
          cd app/build/outputs/apk/debug
          tar -cvf - *.apk | xz -9 -T8 > 调试版_apk.tar.xz

      - name: 上传调试版 APK 压缩包 (tar.xz)
        uses: actions/upload-artifact@v4
        with:
          name: 调试版_apk_xz
          path: "${{ env.项目目录 }}/app/build/outputs/apk/debug/调试版_apk.tar.xz"

      - name: 上传原始调试版 APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.调试版.outputs.调试版 }}
          path: "${{ env.项目目录 }}/app/build/outputs/apk/debug/*.apk"