name: Build HarmonyOS

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  build-hap:
    name: Build HAP (HarmonyOS)
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl xz-utils zip libglu1-mesa

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup HarmonyOS toolchain
        uses: ErBWs/setup-ohos@v1
        with:
          version: latest
          cache: true

      - name: Setup Flutter for OHOS
        run: |
          git clone -b oh-3.35.7-dev https://gitcode.com/openharmony-tpc/flutter_flutter.git $GITHUB_WORKSPACE/flutter
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Get Flutter dependencies
        run: flutter pub get
        env:
          GIT_LFS_SKIP_SMUDGE: 1

      - name: Add OHOS platform
        run: flutter create --platforms ohos .

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1
      
      - name: Build HAP (release)
        run: flutter build hap --release  --dart-define-from-file=c001apk_release.json

      - name: Package HAP artifact
        run: |
          HAP_PATH="ohos/entry/build/default/outputs/default/entry-default-unsigned.hap"
          if [ -f "$HAP_PATH" ]; then
            cp "$HAP_PATH" "app-unsigned.hap"
          else
            echo "HAP file not found at $HAP_PATH"
            exit 1
          fi

      - name: Upload HAP artifact
        uses: actions/upload-artifact@v4
        with:
          name: HarmonyOS-HAP
          path: app-unsigned.hap
          compression-level: 9